// export const GET_HOSTS_DATA = 'GET_HOSTS_DATA';
export const GET_HOST = 'GET_HOST';
export const ADD_APP_TO_HOST = 'ADD_APP_TO_HOST';
export const REMOVE_APP_FROM_ONE_HOST = 'REMOVE_APP_FROM_ONE_HOST';
export const REMOVE_APP_FROM_ALL_HOSTS = 'REMOVE_APP_FROM_ALL_HOSTS';
