// HOSTS CONST
export const ADD_APP_TO_HOST = 'ADD_APP_TO_HOST';
export const REMOVE_APP_FROM_ONE_HOST = 'REMOVE_APP_FROM_ONE_HOST';
export const REMOVE_APP_FROM_ALL_HOSTS = 'REMOVE_APP_FROM_ALL_HOSTS';

// LAYOUT CONSTS
export const CHANGE_LAYOUT = 'CHANGE_LAYOUT';